---
apiVersion: v1
kind: Service
metadata:
  name: sample-clusters
    
spec:
  type: LoadBalancer
  selector:
    app: sample-clusters
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP


---
apiVersion: v1
kind: Service
metadata:
  name: covid19analysis
  labels:
    app: covid19analysis
spec:
  type: LoadBalancer
  selector:
    app: covid19analysis
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
