apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-clusters
  labels:
    app: sample-clusters
  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sampleclusters
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sampleclusters
    spec:
      containers:
        - image: greentropikal/covid19-analysis:latest
          imagePullPolicy: Always
          name: sampleclusters
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"